containers:
- name: nkp-demo
  image: ghcr.io/<YOUR_USER_NAME>/nkp-ci-cd-demo:v202511041229
  ports:
  - containerPort: 8080
  env:
  - name: APP_VERSION
    value: "v1.2"
  - name: BUILD_VERSION
    value: "v202511041229"
