apiVersion: apps/v1
kind: Deployment
metadata:
  name: nkp-demo-app
  labels:
    app: nkp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nkp-demo
  template:
    metadata:
      labels:
        app: nkp-demo
    spec:
      containers:
        - name: nkp-demo
          image: ghcr.io/pauldjmetsi/nkp-ci-cd-demo:v202511041229
          ports:
            - containerPort: 8080
          env:
            - name: APP_VERSION
              value: "v1.2"
            - name: BUILD_VERSION
              value: "v202511041229"
